In [3]:
import numpy as np
print("numpy imported successfully !!")

numpy imported successfully !!


In [4]:
## numpy is starts with Array creation
ls = [25,14,36,96,85,74,41,52,636,545,55]
arr = np.array(ls)
arr

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55])

In [5]:
type(arr) # nd means n dimensional array

numpy.ndarray

In [6]:
## array creation
ls = [25,14,36,96,85,74,41,52,636,545,55,'upflairs']
arr = np.array(ls)
arr
# if there is no similar type of data in list then 
#it will convert all the data in similar data type
# in above all the data converted into string

array(['25', '14', '36', '96', '85', '74', '41', '52', '636', '545', '55',
       'upflairs'], dtype='<U11')

In [7]:
## array creation
ls = [25,14,36,96,85,74,41,52,636,545,55,10.5]
arr = np.array(ls)
arr
# if there is no similar type of data in list then 
#it will convert all the data in similar data type
# in above all the data converted into float

array([ 25. ,  14. ,  36. ,  96. ,  85. ,  74. ,  41. ,  52. , 636. ,
       545. ,  55. ,  10.5])

In [23]:
ls = [25,14,36,96,85,74,41,52,636,545,55,251]
arr = np.array(ls)
arr

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55, 251])

In [24]:
 # both the method is use to find the length or size of array
len(arr) 

12

In [25]:
arr.size

12

In [14]:
arr.dtype  # it will give the type of data

dtype('int32')

In [26]:
## we can access the elements of array by uisng indexing
arr[1]

14

In [27]:
arr[1:]

array([ 14,  36,  96,  85,  74,  41,  52, 636, 545,  55, 251])

In [28]:
arr[-3:] # find last 3 element by using -ve indexing

array([545,  55, 251])

In [32]:
arr[9:] # find last 3 element by using +ve indexing

array([545,  55, 251])

In [36]:
arr[::-1]

array([251,  55, 545, 636,  52,  41,  74,  85,  96,  36,  14,  25])

In [38]:
arr

array([ 25,  14,  36,  96,  85,  74,  41,  52, 636, 545,  55, 251])

In [42]:
np.arange(1,10) # to create a quick array we use arange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# range(start,stop,jump) it will create a quick numpy array in a range
arr2 =np.arange(0,101,2)
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [44]:
arr2.size

51

In [45]:
# ones() will create a quick numpy array with filling with one
# it will get one argument which is sixe of the array you want to cerate
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
# np.zeros() it will fill this array with zeros

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
# linspace() it will crete a quick numpy arrar
np.linspace(1,50,20) 

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [60]:
# random.randint(start,end,no of elements)
# it will create a random quick array betwen 
#start to end and no of elements
arr1 =np.random.randint(1,200,500)
arr1

array([138,  59,  73,  96,  56, 184, 114,   5, 190,  16, 108, 144,  55,
       139,  65,  24, 185, 128,  55, 127,  32,  70, 144, 159,  33, 173,
       168, 173,  17,  49,  15, 127,  38, 190,  48,  84,  53,   8,  29,
         6,  38, 193,  19, 119, 149,  60, 127,  95,  81,  88,  30, 159,
         1,  40, 128,   3, 110, 130, 161, 123, 104, 178, 108,  71,  92,
         3, 101,  61,  44, 115,  74, 173, 132,  46, 191, 180, 102, 185,
       179,  66,  67, 128, 118,  69, 130,  66, 101, 134,  63, 187,  12,
       185,  78,  84, 125,  13, 116,  60, 116, 117,  23,  42,  27, 188,
       166,  18,  22, 106, 180, 142,  24, 133, 105, 163, 106,  47,  32,
       112,  27,  64,  99,  67, 166, 102,  91,  53,   9,   1,  29, 183,
       165,  52, 137, 137,  58,  89, 176, 174, 174,  27, 111, 165, 155,
        49, 105,  58,  74, 171, 117, 134, 191, 153,  47,  16, 103, 191,
        64, 175, 138, 112, 156, 186, 126,  83, 166,  55,  44,  70, 186,
       154,  75, 125, 175,  87, 170,  26,  61, 136,  73, 189, 11

In [64]:
#quiz: filter all items that are less then or equals to 70
# how many items are preseent in your array

filtered_arr = arr1[arr1 <= 70]

len(filtered_arr)

171

In [10]:
import numpy as np

arr3d = np.random.randint(5,200,(5,10,5))
arr3d

array([[[189,  35,  30, 185, 128],
        [157,  59,  72,  13, 174],
        [ 83,  57,  49,  14, 173],
        [170, 147, 158,   6,   6],
        [  6, 191, 145, 158,   9],
        [157,  13,  91,  83,  79],
        [144, 115,  59, 167, 187],
        [180,  14, 144, 104, 188],
        [164, 150,  15, 186, 128],
        [ 91, 111, 143,  41, 118]],

       [[ 33,  14, 191, 141,  36],
        [176, 192,  67, 118, 139],
        [ 89, 148,   6, 119,   6],
        [115,  86,  59,  29, 154],
        [ 69,  60, 193,  38, 129],
        [ 44, 175, 116, 134,  43],
        [112, 151,  24,  28, 127],
        [ 78, 159,  86,   5, 160],
        [ 39,  85,  28, 189,  37],
        [121,  63, 104, 170, 144]],

       [[ 49,  36, 197, 131,  27],
        [ 84,   8, 160,  33, 196],
        [ 73, 180,  11,  87, 129],
        [ 75, 133,  10, 156, 188],
        [181, 172, 169, 168, 128],
        [ 69,  82, 147,   6, 133],
        [ 55, 128,  81,  36, 132],
        [ 40, 168, 174,  23, 104],
        [156, 19

In [11]:
arr3d.shape

(5, 10, 5)

In [ ]:
#(5, 10, 5)
#5 ==> tables
#10 ==>Rows
#5 ==> Columns

In [12]:
arr3d[0] # 

array([[189,  35,  30, 185, 128],
       [157,  59,  72,  13, 174],
       [ 83,  57,  49,  14, 173],
       [170, 147, 158,   6,   6],
       [  6, 191, 145, 158,   9],
       [157,  13,  91,  83,  79],
       [144, 115,  59, 167, 187],
       [180,  14, 144, 104, 188],
       [164, 150,  15, 186, 128],
       [ 91, 111, 143,  41, 118]])

In [13]:
arr3d

array([[[189,  35,  30, 185, 128],
        [157,  59,  72,  13, 174],
        [ 83,  57,  49,  14, 173],
        [170, 147, 158,   6,   6],
        [  6, 191, 145, 158,   9],
        [157,  13,  91,  83,  79],
        [144, 115,  59, 167, 187],
        [180,  14, 144, 104, 188],
        [164, 150,  15, 186, 128],
        [ 91, 111, 143,  41, 118]],

       [[ 33,  14, 191, 141,  36],
        [176, 192,  67, 118, 139],
        [ 89, 148,   6, 119,   6],
        [115,  86,  59,  29, 154],
        [ 69,  60, 193,  38, 129],
        [ 44, 175, 116, 134,  43],
        [112, 151,  24,  28, 127],
        [ 78, 159,  86,   5, 160],
        [ 39,  85,  28, 189,  37],
        [121,  63, 104, 170, 144]],

       [[ 49,  36, 197, 131,  27],
        [ 84,   8, 160,  33, 196],
        [ 73, 180,  11,  87, 129],
        [ 75, 133,  10, 156, 188],
        [181, 172, 169, 168, 128],
        [ 69,  82, 147,   6, 133],
        [ 55, 128,  81,  36, 132],
        [ 40, 168, 174,  23, 104],
        [156, 19

In [17]:
arr3d[1,6:]

array([[112, 151,  24,  28, 127],
       [ 78, 159,  86,   5, 160],
       [ 39,  85,  28, 189,  37],
       [121,  63, 104, 170, 144]])

In [20]:
arr3d[0:,6:]

array([[[144, 115,  59, 167, 187],
        [180,  14, 144, 104, 188],
        [164, 150,  15, 186, 128],
        [ 91, 111, 143,  41, 118]],

       [[112, 151,  24,  28, 127],
        [ 78, 159,  86,   5, 160],
        [ 39,  85,  28, 189,  37],
        [121,  63, 104, 170, 144]],

       [[ 55, 128,  81,  36, 132],
        [ 40, 168, 174,  23, 104],
        [156, 199,  93, 174,  31],
        [124, 127,  30,  42,  68]],

       [[173,   8, 184, 107,  73],
        [ 88, 123,  81, 175, 119],
        [102, 106, 110,  84, 147],
        [ 12,  79, 183,  76, 198]],

       [[ 72,  36, 193, 154,  86],
        [ 37, 134,  90, 149, 111],
        [138,  76, 139, 106,  88],
        [ 53, 131,  24, 170, 187]]])

In [35]:
arr3d[0:,9]

array([[ 91, 111, 143,  41, 118],
       [121,  63, 104, 170, 144],
       [124, 127,  30,  42,  68],
       [ 12,  79, 183,  76, 198],
       [ 53, 131,  24, 170, 187]])

In [36]:
arr3d[0:,9:]

array([[[ 91, 111, 143,  41, 118]],

       [[121,  63, 104, 170, 144]],

       [[124, 127,  30,  42,  68]],

       [[ 12,  79, 183,  76, 198]],

       [[ 53, 131,  24, 170, 187]]])

In [44]:
arr3d[-1,-1,-1] =500


In [45]:
arr3d[-1,-1,-1]

500

In [47]:
arr = np.arange(60)

In [50]:
# to convert one D array into 2 or mor dimension array
# reshape()

arr.reshape(20,3) # 2dimension

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [60]:
arr2 = arr.reshape(3,10,2)

In [61]:
arr2.revel() # this function will convert to any dimension array to one dimension array

AttributeError: 'numpy.ndarray' object has no attribute 'revel'

In [62]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [64]:
arr4 = np.random.randint(1,200,(5,3))
arr4

array([[ 38,  54, 161],
       [151,  54, 140],
       [ 17, 152, 164],
       [ 52, 127,  77],
       [ 57, 151, 148]])

In [65]:
arr4.shape

(5, 3)

In [67]:
np.transpose(arr4).shape

(3, 5)

In [68]:
arr4.T

array([[ 38, 151,  17,  52,  57],
       [ 54,  54, 152, 127, 151],
       [161, 140, 164,  77, 148]])

In [73]:
 arr5 = arr4.flatten()
arr5

array([ 38,  54, 161, 151,  54, 140,  17, 152, 164,  52, 127,  77,  57,
       151, 148])

In [74]:
arr5.min() #to find minimum

17

In [77]:
arr5.max() #to find maximum

164

In [78]:
arr5.mean() # to find mean

102.86666666666666

In [80]:
np.median(arr5)

127.0

In [83]:
arr6 = np.array([9,7,8])
arr6

array([9, 7, 8])

In [84]:
# arr.argmin() it will show the index of minumimum value
arr6.argmin()

1

In [86]:
arr6.argmax() # it will returns the inde value of max value

0

In [88]:
# arr.sort() it will sort the array in ascendiong order
arr6.sort()
arr6

array([7, 8, 9])

In [89]:
arr6[::-1]

array([9, 8, 7])

In [91]:
arr7 =np.array([9,7,8])
arr7

array([9, 7, 8])

In [93]:
arr7.argsort() # this will return the index value in the order of asending

array([1, 2, 0], dtype=int64)